name: build docker and update k8s manifest
  
on:
  workflow_dispatch:
permissions:
  contents: write  # ✅ allow push to the repo

jobs:
  build_docker:
    runs-on: ubuntu-latest

    env:
      ECR_REPO: 279205476473.dkr.ecr.us-east-1.amazonaws.com/myapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Docker login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ env.ECR_REPO }}:$IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPO }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          format: table
          ignore-unfixed: true
          scanners: vuln
          exit-code: 1

      - name: Push image to ECR
        run: docker push ${{ env.ECR_REPO }}:$IMAGE_TAG

      - name: Update manifest file
        run: |
          sed -Ei "s|(image: ?).*|\1${ECR_REPO}:${IMAGE_TAG}|g" manifest.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.yaml
          git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"


      - name: Create PR to main (for ArgoCD)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-${{ env.IMAGE_TAG }}
          title: "Promote image to production (${{ env.IMAGE_TAG }})"
          body: "Promoting release ${{ env.IMAGE_TAG }} to production"






